"""Generate ``r2r3_report.md`` — dataset-driven R2/R3 model study.

Builds on ``r2r3_model.py`` (plan.md Stage 2.4): fits Models A-D on
``examples_eq_results.csv``, scores predicted R2, selects the simplest
model capturing most of the available accuracy, and documents the fitted
priors for use by the estimator (plan.md Stage 2.5).

Usage:
    python r2r3_report.py [output_markdown]
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

import r2r3_model as m

DEFAULT_OUTPUT_MD = Path(__file__).resolve().parent / "r2r3_report.md"


def model_metrics_rows() -> tuple[list[str], dict, str]:
    """Return (markdown table rows, scores dict, selected model name)."""
    df = m.valid_rows(m.add_slip(m.load_results()))
    rows, selected = m.score_table(df)
    scores = {r["name"]: r for r in rows}
    lines = []
    for r in rows:
        mark = " (selected)" if r["name"] == selected else ""
        lines.append(
            f"| {r['name']}{mark} | {r['MAE_ohm']:.4f} | {r['RMSE_ohm']:.4f} | "
            f"{r['MAE_rel']*100:.2f}% | {r['RMSE_rel']*100:.2f}% | "
            f"{r['P10_rel']*100:.2f}% | {r['P50_rel']*100:.2f}% | {r['P90_rel']*100:.2f}% |"
        )
    return lines, scores, selected


def model_d_table(params: dict) -> list:
    lines = []
    for pole in sorted(params):
        p = params[pole]
        ratio = np.exp(p["b"]) * 0.01**p["a"] * 1.0**p["c"]
        lines.append(
            f"| {pole} | {p['a']:.3f} | {p['c']:.3f} | {p['b']:.3f} | "
            f"`{np.exp(p['b']):.4g} * s_fl^{p['a']:.4f} * HP^{p['c']:.4f}` | "
            f"{ratio:.3f} |"
        )
    return lines


def build_markdown() -> str:
    df_full = m.add_slip(m.load_results())
    df = m.valid_rows(df_full)
    n_total, n_valid = len(df_full), len(df)

    metrics_lines, scores, selected = model_metrics_rows()
    params_c = m.fit_model_c(df)
    params_d = m.fit_model_d(df)
    grouping = m.grouping_score_table(df)

    viol = df_full[df_full["R2"] > df_full["R3"]]
    n_viol = len(viol)
    max_ratio = viol["R2"].div(viol["R3"]).max() if n_viol else float("nan")

    best_rmse = min(r["RMSE_rel"] for r in scores.values())
    gain_over_c = (scores["C"]["RMSE_rel"] - scores["D"]["RMSE_rel"]) * 100

    lines = [
        "# R2/R3 Dataset-Driven Model (plan.md Stage 2.4)",
        "",
        "> Auto-generated by `typical_value/r2r3_report.py`.",
        "",
        "## 1. Objective",
        "",
        "Estimate the running/standstill rotor resistance ratio `R2/R3` as an empirical "
        "function of nameplate-available quantities, so `R2` can be derived from the "
        "measured locked-rotor resistance `R3`. The exact skin-effect formula cannot be "
        "used because it requires bar depth / material properties (`h`, `mu`, `sigma`) "
        "not available to the user (plan.md Stage 2.2).",
        "",
        "## 2. Models",
        "",
        "Power-law priors fitted in log-log space:",
        "",
        "| Model | Predictors |",
        "|---|---|",
        "| A | constant |",
        "| B | `s_fl` |",
        "| C | `s_fl`, pole count |",
        "| D | `s_fl`, pole count, HP |",
        "",
        "Enclosure-based variants (frame-size prefix / full frame size) were dropped by "
        "review — the frame-size code is not a dependable enclosure proxy.",
        "",
        "## 3. Data preparation",
        "",
        f"- Source: `typical_value/examples_eq_results.csv` ({n_total} rows).",
        f"- Full-load slip computed from nameplate: `s_fl = (n_s - RPM)/n_s`, "
        f"`n_s = 120*f/poles`.",
        f"- Rows excluded from fitting: `s_fl <= 0` or `HP <= 0` ({n_total - n_valid}).",
        f"- Valid rows used: **{n_valid}**.",
        f"- `R3 >= R2` violations: {n_viol} rows (all floating-point ties at "
        f"ratio = 1.000000, max = {max_ratio:.6f}; no genuine R2 > R3 case).",
        "",
        "## 4. Model scoring",
        "",
        "Each model predicts `R2 = F(...) * R3`; metrics on predicted vs dataset R2.",
        "",
        "| Model | MAE (ohm) | RMSE (ohm) | MAE (%) | RMSE (%) | P10 (%) | P50 (%) | P90 (%) |",
        "|---|---|---|---|---|---|---|---|",
        *metrics_lines,
        "",
        f"Best RMSE_rel: {best_rmse*100:.2f}%. Selected model **{selected}** — the "
        "simplest model whose RMSE is within the 5% tolerance of the best "
        "(plan.md Stage 2.4).",
        "",
    ]

    if selected == "D":
        lines += [
            "## 5. Fitted parameters — Model D (per pole count)",
            "",
            "| Poles | a | c (HP exp) | b | R2/R3 = | R2/R3 @ s_fl=1%, HP=1 |",
            "|---|---|---|---|---|---|",
            *model_d_table(params_d),
            "",
        ]
        lines += [
            "Model C coefficients for reference: ",
            f"`{( {int(p): {k: round(v, 4) for k, v in d.items()} for p, d in params_c.items()} )}`.",
            "",
        ]
    else:
        lines += [
            "## 5. Fitted parameters",
            "",
            f"Selected model {selected} uses the global slip power law; coefficients: see "
            "`r2r3_model.fit_model_b`. (Model D per-pole coefficients available via "
            "`r2r3_model.fit_model_d`.)",
            "",
        ]

    lines += [
        "## 6. Grouping-constant exploration (saved for reference)",
        "",
        "Alternative formulation: a **constant** geometric-mean `R2/R3` per group "
        "(no slip dependence). In-sample error vs a slip-free grouping:",
        "",
        "| Grouping | Groups | RMSE (%) | MAE (%) |",
        "|---|---|---|---|",
    ]
    lines += [
        f"| {g['label']} | {g['n_groups']} | {g['RMSE_rel']*100:.2f}% | {g['MAE_rel']*100:.2f}% |"
        for g in grouping
    ]
    lines += [
        "",
        "Groupings without slip (voltage / pole / HP bucket / combos) lose badly to any "
        "slip-based model (A–D). Slip is the dominant predictor; HP adds value on top of "
        "slip. A slip-bin grouped table matches Model D only with ~100+ entries, so the "
        "power-law prior is preferred.",
        "",
        "## 7. Use in the estimator (plan.md Stage 2.5)",
        "",
        "- Prior: `R2_prior = R3 * exp(b) * s_fl^a * HP^c` using the selected model's "
        "coefficients.",
        f"- Prior spread: `RMSE_rel = {scores[selected]['RMSE_rel']*100:.1f}%`; P10–P90 "
        f"= {scores[selected]['P10_rel']*100:.1f}% to "
        f"{scores[selected]['P90_rel']*100:.1f}%.",
        "- This feeds `R2_prior` and `sigma_R2` in the long-term estimator architecture "
        "(`r_R2 = log(R2/R2_prior)/sigma_R2`).",
        "",
        "## 8. Engineering notes",
        "",
        "- Slip is the dominant predictor: Model B cuts RMSE from ~72% (Model A) to "
        "~33%.",
        f"- Modelling with HP: Model D gains `{gain_over_c:.1f} pp` RMSE over Model C.",
        "- In-sample scoring only; a train/test split is recommended once the prior is "
        "integrated into the estimator.",
        "",
    ]
    return "\n".join(lines)


def write_report(path: str | Path = DEFAULT_OUTPUT_MD) -> None:
    Path(path).write_text(build_markdown(), encoding="utf-8")
    print(f"Wrote {path}")


def main() -> int:
    path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_OUTPUT_MD
    write_report(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())